name: crud-app
version: 0.1.0.0
github: "githubuser/crud-app"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/crud-app#readme>

dependencies:
  - base >= 4.7 && < 5
  - base-compat
  - network
  - aeson
  - wai
  - generics-sop
  - warp
  - text
  - postgresql-libpq
  - time
  - transformers
  - persistent-postgresql
  - servant-server
  - servant-client
  - monad-logger
  - servant
  - servant-server
  - mtl
  - aeson
  - bytestring
  - string-conversions
  - http-media
  - network-uri
  - blaze-html
  - blaze-markup
  - lucid
  - attoparsec
  - directory
  - persistent

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  crud-app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crud-app

tests:
  crud-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crud-app
